"""init

Revision ID: 116c1b8b3247
Revises: 
Create Date: 2026-05-03 14:57:18.627207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116c1b8b3247'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('apple_user_id', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), server_default='free', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apple_user_id')
    )
    op.create_table('collection',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('set_code', sa.String(), nullable=True),
    sa.Column('set_number', sa.String(), nullable=True),
    sa.Column('language', sa.String(), server_default='english', nullable=True),
    sa.Column('market_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_source', sa.String(), nullable=True),
    sa.Column('scanned_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collection_user_active', 'collection', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_collection_user_active', table_name='collection', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('collection')
    op.drop_table('users')
    # ### end Alembic commands ###
